// src/App.vue
<template>
  <view class="app">
    <!-- 这里是应用的根容器 -->
  </view>
</template>

<script setup lang="ts">
import { onLaunch, onShow, onHide } from '@dcloudio/uni-app'
import { useUserStore } from '@/stores/user'

const userStore = useUserStore()

onLaunch(() => {
  console.log('意涵自习室应用启动')
  
  // 检查登录状态
  checkLoginStatus()
  
  // 获取系统信息
  getSystemInfo()
  
  // 检查更新
  checkForUpdate()
})

onShow(() => {
  console.log('应用显示')
})

onHide(() => {
  console.log('应用隐藏')
})

// 检查登录状态
const checkLoginStatus = () => {
  const token = uni.getStorageSync('token')
  if (token) {
    // 验证token有效性
    uni.checkSession({
      success: () => {
        console.log('session有效')
        getUserInfo()
      },
      fail: () => {
        console.log('session失效，清除本地数据')
        uni.removeStorageSync('token')
        uni.removeStorageSync('userInfo')
      }
    })
  }
}

// 获取用户信息
const getUserInfo = async () => {
  try {
    const userInfo = uni.getStorageSync('userInfo')
    if (userInfo) {
      userStore.setUserInfo(userInfo)
    }
  } catch (error) {
    console.error('获取用户信息失败', error)
  }
}

// 获取系统信息
const getSystemInfo = () => {
  uni.getSystemInfo({
    success: (res) => {
      console.log('系统信息', res)
      userStore.setSystemInfo(res)
    }
  })
}

// 检查应用更新
const checkForUpdate = () => {
  // #ifdef MP-WEIXIN
  if (uni.canIUse('getUpdateManager')) {
    const updateManager = uni.getUpdateManager()

    updateManager.onCheckForUpdate((res) => {
      if (res.hasUpdate) {
        console.log('发现新版本')
      }
    })

    updateManager.onUpdateReady(() => {
      uni.showModal({
        title: '更新提示',
        content: '新版本已准备好，是否重启应用？',
        success: (res) => {
          if (res.confirm) {
            updateManager.applyUpdate()
          }
        }
      })
    })

    updateManager.onUpdateFailed(() => {
      uni.showToast({
        title: '更新失败',
        icon: 'none'
      })
    })
  }
  // #endif
}
</script>

<style lang="scss">
/* 应用全局样式 */
.app {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
}
</style>

// src/app.tsx
import { Component } from 'react'
import { Provider } from 'mobx-react'
import Taro from '@tarojs/taro'
import { store } from '@/store'
import 'taro-ui/dist/style/index.scss'
import './app.scss'

class App extends Component {

  componentDidMount() {
    console.log('意涵自习室应用启动')
    
    // 检查登录状态
    this.checkLoginStatus()
    
    // 获取系统信息
    this.getSystemInfo()
    
    // 检查更新
    this.checkForUpdate()
  }

  componentDidShow() {
    console.log('应用显示')
  }

  componentDidHide() {
    console.log('应用隐藏')
  }

  // 检查登录状态
  checkLoginStatus = () => {
    const token = Taro.getStorageSync('token')
    if (token) {
      // 验证token有效性
      Taro.checkSession({
        success: () => {
          console.log('session有效')
          this.getUserInfo()
        },
        fail: () => {
          console.log('session失效，清除本地数据')
          Taro.removeStorageSync('token')
          Taro.removeStorageSync('userInfo')
        }
      })
    }
  }

  // 获取用户信息
  getUserInfo = async () => {
    try {
      const userInfo = Taro.getStorageSync('userInfo')
      if (userInfo) {
        store.updateUserInfo(userInfo)
      }
    } catch (error) {
      console.error('获取用户信息失败', error)
    }
  }

  // 获取系统信息
  getSystemInfo = () => {
    Taro.getSystemInfo({
      success: (res) => {
        console.log('系统信息', res)
        // 可以将系统信息存储到store中
      }
    })
  }

  // 检查小程序更新
  checkForUpdate = () => {
    if (Taro.canIUse('getUpdateManager')) {
      const updateManager = Taro.getUpdateManager()
      
      updateManager.onCheckForUpdate((res) => {
        if (res.hasUpdate) {
          console.log('发现新版本')
        }
      })
      
      updateManager.onUpdateReady(() => {
        Taro.showModal({
          title: '更新提示',
          content: '新版本已准备好，是否重启应用？',
          success: (res) => {
            if (res.confirm) {
              updateManager.applyUpdate()
            }
          }
        })
      })
      
      updateManager.onUpdateFailed(() => {
        Taro.showToast({
          title: '更新失败',
          icon: 'none'
        })
      })
    }
  }

  // 在 App 类中的 render() 函数没有实际作用
  // 请勿修改此函数
  render() {
    return (
      <Provider store={store}>
        {this.props.children}
      </Provider>
    )
  }
}

export default App
